'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const ROOT=path.join(__dirname,'..'); let A=0;
function check(name,fn){try{fn();A++;console.log('PASS:',name);}catch(e){console.error('FAIL:',name,'—',e.message);process.exitCode=1;}}
const policy=JSON.parse(fs.readFileSync(path.join(ROOT,'config/product-provenance-policy.v5.3.210-p1.3.json'),'utf8'));
const registry=JSON.parse(fs.readFileSync(path.join(ROOT,'data/product-provenance-registry.v5.3.210-p1.3.json'),'utf8'));
const products=[],baseline=[];
for(let i=1;i<=12;i++){
  const n=String(i).padStart(2,'0');
  products.push(...JSON.parse(fs.readFileSync(path.join(ROOT,`data/products.v5.3.210-p1.3.part-${n}.json`),'utf8')));
  baseline.push(...JSON.parse(fs.readFileSync(path.join(ROOT,`data/products.v5.3.190.part-${n}.json`),'utf8')));
}
const fields=policy.nutrient_fields;
check('registry and dataset contain 1105 products',()=>{assert.equal(registry.products_count,1105);assert.equal(products.length,1105)});
check('product keys are unique',()=>assert.equal(new Set(products.map(x=>x.key)).size,1105));
check('all products use P1.3 schema',()=>assert.ok(products.every(x=>x.product_db_schema_version==='v5.3.210-p1.3-product-provenance')));
check('all products have canonical quality metadata',()=>assert.ok(products.every(x=>x.data_quality_v1_3&&x.data_quality_v1_3.source_registry_id&&x.data_quality_v1_3.source_kind&&x.data_quality_v1_3.review_status)));
check('no unresolved or blocked products',()=>assert.ok(products.every(x=>x.data_quality_v1_3.source_kind!=='UNRESOLVED'&&x.data_quality_v1_3.review_status!=='BLOCKED')));
check('every nutrient is classified exactly once',()=>{for(const p of products){const seen=[];for(const arr of Object.values(p.nutrient_provenance_v1_3||{}))seen.push(...arr);assert.equal(seen.length,fields.length,p.key);assert.equal(new Set(seen).size,fields.length,p.key);assert.deepEqual([...seen].sort(),[...fields].sort(),p.key)}});
check('every numeric zero has explicit zero semantics',()=>{for(const p of products)for(const f of fields)if(p[f]===0){let m='';for(const [method,arr] of Object.entries(p.nutrient_provenance_v1_3))if(arr.includes(f))m=method;assert.ok(['SOURCE_REPORTED_ZERO','ASSUMED_ZERO'].includes(m),`${p.key}:${f}:${m}`)}});
check('unknown zero list equals ASSUMED_ZERO group',()=>{for(const p of products)assert.deepEqual([...(p.unknown_zero_fields_v1_3||[])].sort(),[...(p.nutrient_provenance_v1_3.ASSUMED_ZERO||[])].sort(),p.key)});
check('P1.3 migration preserves all numeric nutrient values',()=>{const old=new Map(baseline.map(x=>[x.key,x]));for(const p of products){const b=old.get(p.key);assert.ok(b,p.key);for(const f of fields)assert.strictEqual(p[f],b[f],`${p.key}:${f}`)}});
check('HIGH confidence is restricted to primary datasets',()=>assert.ok(products.every(p=>p.data_quality_v1_3.confidence_tier!=='HIGH'||p.data_quality_v1_3.source_kind==='PRIMARY_DATASET')));
check('statistics are internally consistent',()=>{assert.deepEqual(registry.statistics.confidence_tiers,{HIGH:263,LOW:28,MEDIUM:814});assert.equal(registry.statistics.assumed_zero_products,775);assert.equal(registry.statistics.assumed_zero_fields,3577);assert.equal(Object.values(registry.statistics.source_kinds).reduce((a,b)=>a+b,0),1105)});
check('generated JS product chunks match JSON chunks',()=>{const ctx={window:{}};vm.createContext(ctx);for(let i=1;i<=12;i++){const n=String(i).padStart(2,'0');vm.runInContext(fs.readFileSync(path.join(ROOT,`assets/data/products.v5.3.210-p1.3.part-${n}.js`),'utf8'),ctx)}const js=ctx.window.__PRODUCT_SCRIPT_CHUNKS__.flat();assert.equal(js.length,products.length);assert.deepEqual(JSON.parse(JSON.stringify(js)),products)});
check('runtime provenance registry matches JSON registry',()=>{const ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(ROOT,'assets/data/product-provenance-registry.v5.3.210-p1.3.js'),'utf8'),ctx);assert.deepEqual(JSON.parse(JSON.stringify(ctx.window.__PRODUCT_PROVENANCE_REGISTRY__)),registry)});
check('runtime quality engine reports uncertainty and assumed zeros',()=>{const ctx={window:{},console};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(ROOT,'assets/data/product-provenance-registry.v5.3.210-p1.3.js'),'utf8'),ctx);vm.runInContext(fs.readFileSync(path.join(ROOT,'assets/js/02-product-data-quality-v5.3.210-p1.3.js'),'utf8'),ctx);const byKey=new Map(products.map(x=>[x.key,x]));const out=ctx.window.ProductDataQualityV13.analyzeRation([{key:'ayran',grams:200},{key:'ghee',grams:10}],{byKey},['kcal','fiber']);assert.equal(out.version,'v5.3.210-p1.3');assert.ok(out.nutrients.kcal.uncertainty_abs>0);assert.ok(out.nutrients.fiber.assumed_zero_products>=1);assert.ok(out.summary.assumed_zero_products>=1)});
check('runtime manifest loads P1.3 products and quality engine before app core',()=>{const cfg=JSON.parse(fs.readFileSync(path.join(ROOT,'config/runtime-assets.v5.3.210-pc2.json'),'utf8'));assert.equal(cfg.release_version,'v5.3.210-pc2');assert.equal(cfg.product_json_chunks.length,12);assert.ok(cfg.product_json_chunks.every(x=>x.includes('products.v5.3.210-p1.3.')));const q=cfg.modern_core_scripts.findIndex(x=>x.includes('02-product-data-quality'));const core=cfg.modern_core_scripts.findIndex(x=>x.includes('03-app-core'));assert.ok(q>=0&&q<core)});
check('legacy runtime carries the same P1.3 quality controls',()=>{assert.ok(fs.readFileSync(path.join(ROOT,'assets/legacy/js/03-app-core-v5.3.208.js'),'utf8').includes('dataQuality:'));assert.ok(fs.readFileSync(path.join(ROOT,'assets/legacy/js/61-ai-nutrition-planner-v5.3.210.js'),'utf8').includes('data_quality'));assert.ok(fs.readFileSync(path.join(ROOT,'assets/legacy/js/29-report-builder-v5.js'),'utf8').includes('Оценочная неопределённость'));assert.deepEqual(fs.readFileSync(path.join(ROOT,'assets/legacy/js/02-product-data-quality-v5.3.210-p1.3.js')),fs.readFileSync(path.join(ROOT,'assets/js/02-product-data-quality-v5.3.210-p1.3.js')))});
check('AI guard clamps language to data quality',()=>{const client=fs.readFileSync(path.join(ROOT,'assets/js/61-ai-nutrition-planner-v5.3.210.js'),'utf8');const server=fs.readFileSync(path.join(ROOT,'api/gemini.php'),'utf8');assert.ok(client.includes('data_quality'));assert.ok(server.includes('ASSUMED_ZERO'));assert.ok(server.includes('MEDIUM'));assert.ok(server.includes('LOW'))});
check('patient report exposes uncertainty and zero caveat',()=>{const report=fs.readFileSync(path.join(ROOT,'assets/js/29-report-builder-v5.js'),'utf8');assert.ok(report.includes('Оценочная неопределённость'));assert.ok(report.includes('Условный ноль означает'));assert.ok(report.includes('provenanceQuality'))});
check('analytical artifacts exist and queue is explicit',()=>{const a=JSON.parse(fs.readFileSync(path.join(ROOT,'reports/p1-3b-analytics.json'),'utf8'));assert.equal(a.failures.length,0);assert.equal(a.review_queue_count,62);assert.ok(fs.statSync(path.join(ROOT,'NUTRITION_CALCULATOR_V5_3_210_P1_3_REVIEW_QUEUE.csv')).size>1000)});
console.log(JSON.stringify({status:process.exitCode?'FAIL':'PASS',assertions:A,products:products.length,nutrients:fields.length},null,2));
if(process.exitCode)process.exit(process.exitCode);
