'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const ROOT=path.resolve(__dirname,'..');
const cfg=JSON.parse(fs.readFileSync(path.join(ROOT,'config/runtime-assets.v5.3.210-rc2.json'),'utf8'));
const js=fs.readFileSync(path.join(ROOT,'assets/js/83-workspace-correction-v5.3.210-rc2-hf11.js'),'utf8');
const nav=fs.readFileSync(path.join(ROOT,'assets/js/75-navigation-shell-v5.3.210-rc2-hf11.js'),'utf8');
const css=fs.readFileSync(path.join(ROOT,'assets/css/workspace-correction-v5.3.210-rc2-hf11.css'),'utf8');
let pass=0;
function check(name,fn){try{fn();pass++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e.message);process.exitCode=1;}}
check('dedicated correction workspace is registered',()=>assert.ok(js.includes("panel.id='workspaceCorrectionPanel'")&&nav.includes("ids:['workspaceCorrectionPanel']")));
check('three priorities remain the upper bound',()=>assert.ok(js.includes('return out.slice(0,3)')));
check('selected direction is shown before other directions',()=>assert.ok(js.indexOf('workspaceCorrectionWorkbench')<js.indexOf('workspaceCorrectionPriorities')));
check('other directions are compact rather than repeated cards',()=>assert.ok(js.includes('workspace-priority-chip')&&!js.includes('Что стоит изменить сейчас')));
check('priority language distinguishes excess and deficiency',()=>assert.ok(js.includes('Главный источник превышения')&&js.includes('Сейчас больше всего поступает из')));
check('recommended limit language is not mislabeled as UL',()=>assert.ok(js.includes('Выше рекомендуемого ограничения')&&js.includes('Выше применимого верхнего уровня')));
check('meaningful improvement gate exists',()=>assert.ok(js.includes('targetResult.meaningful')&&js.includes('displayChanged')&&js.includes('gapClosed')));
check('realistic portion gate exists',()=>assert.ok(js.includes('portionCheck')&&js.includes('portionCap')&&js.includes('чрезмерная порция')));
check('weak or unrealistic scenarios are not candidates',()=>assert.ok(js.includes('candidate:false')&&js.includes('scenarioBurden(s)')));
check('simple quantity failure has an honest fallback',()=>assert.ok(js.includes('Простого изменения количества недостаточно')&&js.includes('Нужен другой источник')));
check('variant labels describe the actual action',()=>assert.ok(js.includes("'Уменьшить до '")&&js.includes("'Увеличить до '")));
check('manual grams remain secondary',()=>assert.ok(js.includes('Настроить количество вручную')&&js.includes('workspaceCorrectionProduct')&&js.includes('workspaceCorrectionGrams')));
check('preview remains canonical and non-mutating',()=>assert.ok(js.includes('core().snapshot(draftRation')&&js.includes('HEIRuntimeV2')&&js.includes("status:'draft'")));
check('apply is conditional on verdict',()=>assert.ok(js.includes('v.applyAllowed')&&js.includes('Не применять автоматически')));
check('review state requires an explicit second confirmation',()=>assert.ok(js.includes('Проверить последствия')&&js.includes('Подтвердить применение')&&js.includes('reviewConfirmedScenarioId')&&js.includes('Вариант неоднозначный')));
check('different selected contributor is explained',()=>assert.ok(js.includes('этот продукт тоже заметно влияет на показатель')&&css.includes('workspace-correction-selection-note')));
check('manual no-op produces an explanatory verdict',()=>assert.ok(js.includes('if(!contributor)return null')&&js.includes('Этот вариант не решает выбранную задачу')));
check('severe tradeoffs are blocked',()=>assert.ok(js.includes('Вариант не подходит для автоматического применения')&&js.includes('worse>=2')));
check('methodology and AI are separated',()=>assert.ok(js.includes('<summary>Как рассчитан вариант</summary>')&&js.includes('Подобрать другой вариант с ИИ')));
check('mobile bottom navigation clearance is reserved',()=>assert.ok(css.includes('scroll-padding-bottom:112px')&&css.includes('safe-area-inset-bottom')&&!css.includes('position:fixed')));
check('correction profile context is compact',()=>assert.ok(js.includes('workspaceCorrectionPersonSummary')&&css.includes('#workspaceCorrectionPersonSummary')));
check('modern and legacy runtimes load HF11',()=>{const u='./assets/js/83-workspace-correction-v5.3.210-rc2-hf11.js?v=v5.3.210-rc2-hf11';assert.ok(cfg.modern_core_scripts.includes(u));assert.ok(cfg.legacy_core_scripts.includes(u.replace('/js/','/legacy/js/')));});
check('runtime contains HF11 CSS and self-test',()=>{assert.ok(cfg.css_sources.includes('assets/css/workspace-correction-v5.3.210-rc2-hf11.css'));assert.ok(cfg.selftest_scripts.includes('./assets/js/84-workspace-correction-selftest-v5.3.210-rc2-hf11.js?v=v5.3.210-rc2-hf11'));});
check('public API preserves preview apply undo contract',()=>assert.ok(js.includes('w.WorkspaceCorrectionHF11')&&js.includes('preview:preview')&&js.includes('apply:applyScenario')&&js.includes('undo:undo')));
if(!process.exitCode)console.log(`workspace correction HF11: ${pass}/24 checks passed`);
