#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, stat, tempfile, zipfile
from pathlib import Path
from runtime_inventory import compute as compute_runtime

ROOT=Path(__file__).resolve().parents[1]
VERSION='v5.3.210-rc2-hf20'
BASE_VERSION='v5.3.210-rc2'
PRODUCT_BASELINE='v5.3.210-pc2'
FIXED_DT=(2026,7,22,0,0,0)
SOURCE_EXCLUDES={'.git','node_modules','reports','release','__pycache__','.pytest_cache','.mypy_cache','.ruff_cache','playwright-report','test-results','blob-report'}
GENERATED_NAMES={'release-manifest.json','release-sbom.spdx.json'}

def sha(data:bytes)->str:return hashlib.sha256(data).hexdigest()
def mode_for(rel:str)->int:
    return 0o755 if rel.startswith('tools/') or (rel.startswith('tests/') and rel.endswith(('.sh','.py'))) else 0o644

def runtime_files(template=False):
    rels,missing=compute_runtime()
    if missing:raise SystemExit('runtime closure incomplete: '+', '.join(missing))
    out=[]
    for rel in rels:
        p=ROOT/rel
        if rel=='api/gemini-secret.php' and template:p=ROOT/'api/gemini-secret.example.php'
        if not p.is_file():raise SystemExit(f'runtime file missing: {rel}')
        out.append((rel,p.read_bytes(),0o644))
    return out

def project_files(include_secret:bool):
    out=[]
    for p in sorted(ROOT.rglob('*')):
        if not p.is_file():continue
        rel=p.relative_to(ROOT).as_posix()
        if any(part in SOURCE_EXCLUDES for part in Path(rel).parts):continue
        if rel in GENERATED_NAMES:continue
        if not include_secret and rel=='api/gemini-secret.php':continue
        out.append((rel,p.read_bytes(),mode_for(rel)))
    return out

def spdx(files,artifact_name):
    fs=[]
    for rel,data,_ in files:
        fs.append({'SPDXID':'SPDXRef-File-'+hashlib.sha1(rel.encode()).hexdigest(),'fileName':'./'+rel,'checksums':[{'algorithm':'SHA256','checksumValue':sha(data)}],'licenseConcluded':'NOASSERTION','copyrightText':'NOASSERTION'})
    return {'spdxVersion':'SPDX-2.3','dataLicense':'CC0-1.0','SPDXID':'SPDXRef-DOCUMENT','name':artifact_name,'documentNamespace':'https://example.invalid/nutrition-calculator/'+VERSION+'/'+artifact_name,'creationInfo':{'created':'2026-07-22T00:00:00Z','creators':['Tool: nutrition-calculator-release-gate-rc2']},'packages':[{'SPDXID':'SPDXRef-Package-NutritionCalculator','name':'nutrition-calculator','versionInfo':VERSION,'downloadLocation':'NOASSERTION','filesAnalyzed':True,'licenseConcluded':'NOASSERTION','licenseDeclared':'NOASSERTION','copyrightText':'NOASSERTION'}],'files':fs,'relationships':[{'spdxElementId':'SPDXRef-Package-NutritionCalculator','relationshipType':'CONTAINS','relatedSpdxElement':f['SPDXID']} for f in fs]}

def add_entry(zf,rel,data,mode):
    zi=zipfile.ZipInfo(rel,FIXED_DT);zi.compress_type=zipfile.ZIP_DEFLATED;zi.create_system=3;zi.external_attr=(stat.S_IFREG|mode)<<16
    zf.writestr(zi,data,compress_type=zipfile.ZIP_DEFLATED,compresslevel=9)

def build(path:Path,kind:str):
    files=runtime_files(template=kind=='hosting-template') if kind in {'hosting','hosting-template'} else project_files(include_secret=kind=='full')
    runtime_rels,_=compute_runtime()
    all_runtime=[p for top in ('assets','data','api') for p in (ROOT/top).rglob('*') if p.is_file()]
    normative=json.loads((ROOT/'assets/data/normative-registry.v5.3.210-p1.2.json').read_text())
    formulas=json.loads((ROOT/'config/formula-registry.v5.3.210-p1.4.json').read_text())
    gold=json.loads((ROOT/'data/formula-golden-cases.v5.3.210-p1.4.json').read_text())
    provenance=json.loads((ROOT/'data/product-provenance-registry.v5.3.210-p1.3.json').read_text())
    policy=json.loads((ROOT/'config/validation-evidence-policy.v5.3.210-pc2.json').read_text())
    blind=json.loads((ROOT/'validation/P2_0_BLIND_DOMAIN_REVIEW_CASES_RU.json').read_text())
    key=json.loads((ROOT/'validation/P2_0_REFERENCE_ANSWER_KEY_PRIVATE.json').read_text())
    workflow_path=ROOT/'assets/js/67-professional-workflow-restoration-v5.3.210-rc2.js'
    support_path=ROOT/'assets/js/69-release-support-v5.3.210-rc2.js'
    manifest={'schema_version':2,'release_version':VERSION,'product_baseline':PRODUCT_BASELINE,'artifact_kind':kind,'created_at':'2026-07-22T00:00:00Z','architecture':{
      'runtime_manifest':'config/runtime-assets.v5.3.210-rc2.json','runtime_closure_files':len(runtime_rels),'runtime_candidates':len(all_runtime),'pruned_runtime_files':len(all_runtime)-len([x for x in runtime_rels if x.startswith(('assets/','data/','api/'))]),'css_bundle':'assets/css/runtime-bundle-v5.3.210-rc2-hf20.css','css_source_layers':39,
      'normative_registry':{'path':'assets/data/normative-registry.v5.3.210-p1.2.json','version':normative['registry_version'],'sha256':sha((ROOT/'assets/data/normative-registry.v5.3.210-p1.2.json').read_bytes()),'reviewed_at':normative['reviewed_at'],'review_due_at':normative['review_due_at'],'sources':len(normative['sources'])},
      'product_provenance_registry':{'path':'data/product-provenance-registry.v5.3.210-p1.3.json','version':'v5.3.210-p1.3','sha256':sha((ROOT/'data/product-provenance-registry.v5.3.210-p1.3.json').read_bytes()),'products':provenance['products_count']},
      'formula_registry':{'source_path':'config/formula-registry.v5.3.210-p1.4.json','runtime_path':'assets/data/formula-registry.v5.3.210-p1.4.js','version':formulas['registry_version'],'sha256':sha((ROOT/'config/formula-registry.v5.3.210-p1.4.json').read_bytes()),'formulas':len(formulas['formulas']),'golden_cases':len(gold['cases'])},
      'professional_workflow_restoration':{'version':BASE_VERSION,'controller_path':'assets/js/67-professional-workflow-restoration-v5.3.210-rc2.js','legacy_controller_path':'assets/legacy/js/67-professional-workflow-restoration-v5.3.210-rc2.js','css_path':'assets/css/professional-workflow-restoration-v5.3.210-rc2.css','sha256':sha(workflow_path.read_bytes()),'single_professional_mode':True,'explicit_day_confirmation':False,'direct_result_sections':['hei_dashboard','hei_table','daily_totals_and_norms','integrated_diet_matrix','data_quality'],'harvard_plate_collapsible':True,'optional_ai_input_collapsed':True,'protected_context_progressive':True,'removed_active_layers':['pc1_mode_switch','pc1_scope_confirmation','pc2_result_tabs','prominent_validation_panel']},
      'release_support':{'version':BASE_VERSION,'controller_path':'assets/js/69-release-support-v5.3.210-rc2.js','legacy_controller_path':'assets/legacy/js/69-release-support-v5.3.210-rc2.js','css_path':'assets/css/release-support-v5.3.210-rc2.css','sha256':sha(support_path.read_bytes()),'privacy_safe_diagnostics':True,'diagnostic_excludes_user_content':True,'server_health_check':True,'no_prominent_beta_banner':True,'beta_noindex':True,'immutable_versioned_assets':True},
      'hei2020_hotfix3':{'core_path':'assets/js/70-hei2020-core-v5.3.210-rc2-hf3.js','input_adapter_path':'assets/js/71-hei2020-input-adapter-v5.3.210-rc2-hf3.js','interpretation_engine_path':'assets/js/72-diet-interpretation-engine-v5.3.210-rc2-hf3.js','runtime_bridge_path':'assets/js/73-hei2020-runtime-bridge-v5.3.210-rc2-hf3.js','selftest_path':'assets/js/74-hei2020-regression-selftest-v5.3.210-rc2-hf3.js','energy_basis':'actual_ration_energy','added_sugar_kcal_per_tsp_eq':16,'separate_interpretation':True,'compact_progressive_disclosure':True,'uncertainty_escalation_only_near_limits':True,'legacy_contract_preserved':True},
      'workspace_hotfix11':{'controller_path':'assets/js/75-navigation-shell-v5.3.210-rc2-hf11.js','css_path':'assets/css/navigation-shell-v5.3.210-rc2-hf11.css','selftest_path':'assets/js/76-navigation-shell-selftest-v5.3.210-rc2-hf11.js','workspace_slice_path':'assets/js/77-workspace-ration-overview-v5.3.210-rc2-hf8.js','workspace_slice_css':'assets/css/workspace-ration-overview-v5.3.210-rc2-hf8.css','analysis_detail_path':'assets/js/79-workspace-analysis-detail-v5.3.210-rc2-hf7.js','analysis_detail_css':'assets/css/workspace-analysis-detail-v5.3.210-rc2-hf7.css','analysis_detail_selftest':'assets/js/80-workspace-analysis-detail-selftest-v5.3.210-rc2-hf8.js','profile_needs_path':'assets/js/81-workspace-profile-needs-v5.3.210-rc2-hf8.js','profile_needs_css':'assets/css/workspace-profile-needs-v5.3.210-rc2-hf8.css','profile_needs_selftest':'assets/js/82-workspace-profile-needs-selftest-v5.3.210-rc2-hf8.js','correction_path':'assets/js/83-workspace-correction-v5.3.210-rc2-hf11.js','correction_css':'assets/css/workspace-correction-v5.3.210-rc2-hf11.css','correction_selftest':'assets/js/84-workspace-correction-selftest-v5.3.210-rc2-hf11.js','centralized_priorities':True,'decision_first_correction':True,'max_visible_directions':3,'ready_quantity_variants_max':2,'meaningful_contributor_selection':True,'meaningful_effect_gate':True,'realistic_portion_gate':True,'honest_no_simple_scenario':True,'compact_other_directions':True,'conditional_apply':True,'review_secondary_confirmation':True,'selected_contributor_explanation':True,'manual_noop_feedback':True,'severe_tradeoff_block':True,'terminology_split':True,'automatic_preview':True,'progressive_tradeoff_details':True,'manual_mode_secondary':True,'duplicate_workspace_heading_removed':True,'compact_correction_profile_context':True,'correction_mobile_bottom_clearance':True,'canonical_preview_recalculation':True,'single_active_scenario':True,'explicit_apply':True,'one_step_undo':True,'ai_source_separated':True,'methodology_ai_separated':True,'initial_route_without_needs':'profile','returning_default_route':'last_workspace','profile_route':'profile','profile_first':True,'person_context_persists':True,'needs_removed_from_ration':True,'default_mode':'workspace','parallel_opt_in':False,'long_page_fallback':True,'cache_busted_runtime_assets':True,'primary_workspaces':['ration','analysis','correction','report'],'analysis_views':['overview','nutrients','hei'],'hash_routing':True,'history_navigation':True,'per_route_scroll_restoration':True,'legacy_long_page_preserved':True,'mobile_single_bottom_navigation':True,'dedicated_nutrient_view':True,'dedicated_hei_view':True,'canonical_contributors':True,'independent_guardrails':True,'mobile_result_pagination':True,'deep_link_metric_mapping':True},
      'workspace_hotfix12_stage3b':{'controller_path':'assets/js/85-workspace-correction-stage3b-v5.3.210-rc2-hf12.js','legacy_controller_path':'assets/legacy/js/85-workspace-correction-stage3b-v5.3.210-rc2-hf12.js','css_path':'assets/css/workspace-correction-stage3b-v5.3.210-rc2-hf12.css','selftest_path':'assets/js/86-workspace-correction-stage3b-selftest-v5.3.210-rc2-hf12.js','extends':'workspace_hotfix11','replacement_supported':True,'addition_supported':True,'one_active_alternative':True,'candidate_limit':3,'cheap_prefilter_limits':{'replacement':24,'addition':30},'same_food_role_gate':True,'nutrient_family_gate':True,'product_data_quality_gate':True,'concrete_quantities_visible':True,'canonical_snapshot_recalculation':True,'full_hei_recalculation':True,'meaningful_effect_gate_reused':True,'severe_tradeoff_gate_reused':True,'explicit_apply':True,'review_secondary_confirmation':True,'one_step_undo':True,'transactional_undo':True,'composite_replacement_blocked':True,'quantity_path_remains_primary':True,'automatic_whole_diet_optimization':False},
      'workspace_hotfix13_report':{'navigation_controller_path':'assets/js/75-navigation-shell-v5.3.210-rc2-hf13.js','navigation_legacy_path':'assets/legacy/js/75-navigation-shell-v5.3.210-rc2-hf13.js','navigation_css_path':'assets/css/navigation-shell-v5.3.210-rc2-hf13.css','navigation_selftest_path':'assets/js/76-navigation-shell-selftest-v5.3.210-rc2-hf13.js','report_controller_path':'assets/js/87-workspace-report-v5.3.210-rc2-hf13.js','report_legacy_path':'assets/legacy/js/87-workspace-report-v5.3.210-rc2-hf13.js','report_css_path':'assets/css/workspace-report-v5.3.210-rc2-hf13.css','report_selftest_path':'assets/js/88-workspace-report-selftest-v5.3.210-rc2-hf13.js','schema':'nutrition-workspace-report-v1','serializable_model':True,'same_body_renderer_for_preview_print_pdf':True,'canonical_report_snapshot_reused':True,'canonical_analysis_view_model_reused':True,'new_nutrient_calculation':False,'new_hei_calculation':False,'bounded_report_options':5,'explicit_report_options_contract':True,'required_sections_always_included':True,'detailed_nutrients_optional':True,'full_hei_optional':True,'contributors_optional':True,'applied_changes_optional':True,'methodology_optional':True,'independent_guardrails_in_report':True,'technical_hei_units_humanized':True,'focus_preserving_option_refresh':True,'human_product_names_in_changes':True,'legacy_print_buttons_rebound':True,'json_export':True,'mobile_tables_as_cards':True,'old_dom_report_route_replaced':True,'long_page_fallback_preserved':True},
      'workspace_hotfix14_stage4_5':{'extends':'workspace_hotfix13_report','architecture_contract_id':'nutrition-calculator-stage-4-5-architecture-v1','architecture_contract_source':'quality/stage-4-5-architecture-contract.json','navigation_controller_path':'assets/js/75-navigation-shell-v5.3.210-rc2-hf13.js','navigation_legacy_path':'assets/legacy/js/75-navigation-shell-v5.3.210-rc2-hf13.js','navigation_css_path':'assets/css/navigation-shell-v5.3.210-rc2-hf14.css','report_controller_path':'assets/js/87-workspace-report-v5.3.210-rc2-hf14.js','report_legacy_path':'assets/legacy/js/87-workspace-report-v5.3.210-rc2-hf14.js','report_css_path':'assets/css/workspace-report-v5.3.210-rc2-hf14.css','route_ownership_contract_status':'PASSED','full_journey_e2e_defined':True,'full_journey_e2e_status':'PENDING_BROWSER_ENVIRONMENT','viewport_matrix':[[360,800],[390,844],[430,932],[768,1024],[1366,768],[1440,900]],'viewport_e2e_defined':True,'viewport_e2e_status':'PENDING_BROWSER_ENVIRONMENT','print_pdf_e2e_defined':True,'print_pdf_e2e_status':'PENDING_BROWSER_ENVIRONMENT','inactive_focus_contract_status':'PASSED','browser_history_e2e_defined':True,'ration_state_preservation_e2e_defined':True,'canonical_report_parity_e2e_defined':True,'manual_acceptance_status':'PENDING_REAL_DEVICE_REVIEW','mobile_header_overflow_guard':True,'print_long_name_wrapping':True,'print_table_header_repeat':True,'print_row_break_protection':True,'calculation_model_changed':False,'formula_registry_changed':False,'normative_registry_changed':False,'visible_fallback_preserved':True,'stage5a_applied':False},
      'workspace_hotfix15_stage4_6':{'extends':'workspace_hotfix14_stage4_5','daily_cycle_contract_id':'nutrition-calculator-stage-4-6-daily-cycle-v1','daily_cycle_contract_source':'quality/stage-4-6-daily-cycle-contract.json','search_controller_path':'assets/js/08-ux-search-mobile-v5.3.210-rc2-hf15.js','ration_controller_path':'assets/js/77-workspace-ration-overview-v5.3.210-rc2-hf15.js','ration_legacy_path':'assets/legacy/js/77-workspace-ration-overview-v5.3.210-rc2-hf15.js','daily_cycle_css_path':'assets/css/workspace-daily-cycle-v5.3.210-rc2-hf15.css','chromium_acceptance_status':'PASSED','chromium_acceptance_report':'reports/stage-4-6-chromium-acceptance.json','daily_journey_status':'PASSED','viewport_matrix':[[360,800],[390,844],[430,932],[768,1024],[1366,768],[1440,900]],'viewport_matrix_status':'PASSED','print_pdf_status':'PASSED','firefox_status':'PENDING_BROWSER_BINARY','webkit_status':'PENDING_BROWSER_BINARY','manual_acceptance_status':'PENDING_REAL_DEVICE_REVIEW','standard_add_preserves_search_context':True,'explicit_open_ration_action':True,'composite_add_edit_preserved':True,'minimum_action_target_px':44,'sticky_focus_clearance':True,'calculation_model_changed':False,'formula_registry_changed':False,'normative_registry_changed':False,'product_database_changed':False,'meal_data_model_changed':False,'stage5a_applied':False,'long_mode_removed':False},
      'workspace_hotfix16_stage5a':{'extends':'workspace_hotfix15_stage4_6','contract_id':'nutrition-calculator-stage-5a-unified-interface-v1','contract_source':'quality/stage-5a-unified-interface-contract.json','navigation_controller_path':'assets/js/75-navigation-shell-v5.3.210-rc2-hf16.js','navigation_legacy_path':'assets/legacy/js/75-navigation-shell-v5.3.210-rc2-hf16.js','navigation_css_path':'assets/css/navigation-shell-v5.3.210-rc2-hf16.css','navigation_selftest_path':'assets/js/76-navigation-shell-selftest-v5.3.210-rc2-hf16.js','chromium_acceptance_status':'PASSED','chromium_acceptance_report':'reports/stage-5a-chromium-acceptance.json','viewport_matrix':[[360,800],[390,844],[430,932],[768,1024],[1366,768],[1440,900]],'viewport_matrix_status':'PASSED','print_pdf_status':'PASSED','ordinary_mode':'workspace','user_mode_switcher_removed':True,'full_canvas_navigation_removed':True,'technical_long_entry':'?ui=long','technical_long_query_only':True,'technical_long_persisted':False,'stale_long_preference_removed':True,'technical_return_action_count':1,'technical_return_label':'Вернуться к рабочим разделам','route_preserved_on_return':True,'ration_state_preserved_on_return':True,'history_length_preserved_on_fallback_roundtrip':True,'legacy_dom_preserved':True,'legacy_handlers_preserved':True,'long_mode_removed':False,'stage5b_applied':False,'firefox_status':'PENDING_BROWSER_BINARY','webkit_status':'PENDING_BROWSER_BINARY','manual_acceptance_status':'PENDING_REAL_DEVICE_REVIEW','direct_http_navigation_status':'PENDING_EXTERNAL_ENVIRONMENT','calculation_model_changed':False,'formula_registry_changed':False,'normative_registry_changed':False,'product_database_changed':False,'meal_data_model_changed':False},
      'workspace_hotfix17_stage5a_stability':{'extends':'workspace_hotfix16_stage5a','contract_id':'nutrition-calculator-stage-5a-stability-gate-v1','contract_source':'quality/stage-5a-stability-contract.json','navigation_controller_path':'assets/js/75-navigation-shell-v5.3.210-rc2-hf17.js','navigation_legacy_path':'assets/legacy/js/75-navigation-shell-v5.3.210-rc2-hf17.js','navigation_css_path':'assets/css/navigation-shell-v5.3.210-rc2-hf17.css','navigation_selftest_path':'assets/js/76-navigation-shell-selftest-v5.3.210-rc2-hf17.js','chromium_stability_status':'PASSED','chromium_stability_report':'reports/stage-5a-stability-chromium.json','confirmed_hf16_mutation_feedback_loop':True,'hf16_observed_mutations_per_second':7072,'idempotent_visibility_writes':True,'steady_state_mutation_budget_per_second':2,'route_cycles':20,'routes_per_cycle':7,'technical_fallback_roundtrips':4,'external_visibility_drift_repair':True,'corrupted_storage_fail_safe':True,'unrelated_query_parameters_preserved':True,'synthetic_200_percent_text_reflow_status':'PASSED','legacy_dom_preserved':True,'stage5b_applied':False,'firefox_status':'PENDING_BROWSER_BINARY','webkit_status':'PENDING_BROWSER_BINARY','manual_acceptance_status':'PENDING_REAL_DEVICE_REVIEW','direct_http_navigation_status':'PENDING_EXTERNAL_ENVIRONMENT','calculation_model_changed':False,'formula_registry_changed':False,'normative_registry_changed':False,'product_database_changed':False,'meal_data_model_changed':False},
      'workspace_hotfix18_stage5a_final_stability':{'extends':'workspace_hotfix17_stage5a_stability','contract_id':'nutrition-calculator-stage-5a-final-stability-v1','contract_source':'quality/stage-5a-final-stability-contract.json','profile_controller_path':'assets/js/81-workspace-profile-needs-v5.3.210-rc2-hf18.js','profile_legacy_path':'assets/legacy/js/81-workspace-profile-needs-v5.3.210-rc2-hf18.js','profile_selftest_path':'assets/js/82-workspace-profile-needs-selftest-v5.3.210-rc2-hf18.js','norm_controller_path':'assets/js/60-norm-region-clarity-v5.3.210-rc2-hf18.js','norm_legacy_path':'assets/legacy/js/60-norm-region-clarity-v5.3.210-rc2-hf18.js','chromium_final_stability_status':'PASSED','chromium_final_stability_report':'reports/stage-5a-final-stability-chromium.json','full_document_observation_ms':3000,'full_document_mutations':0,'full_document_mutation_budget':2,'profile_norm_refresh_calls':100,'profile_norm_refresh_mutations':0,'profile_norm_refresh_budget':2,'navigation_steady_mutations':0,'navigation_post_settle_mutations':0,'hf17_scope_overstatement_corrected':True,'profile_observer_feedback_loop_fixed':True,'norm_bootstrap_poll_loop_fixed':True,'idempotent_profile_rendering':True,'idempotent_norm_rendering':True,'legacy_dom_preserved':True,'stage5b_applied':False,'firefox_status':'PENDING_EXTERNAL_BROWSER','webkit_status':'PENDING_EXTERNAL_BROWSER','manual_acceptance_status':'PENDING_REAL_DEVICE_REVIEW','direct_http_navigation_status':'PENDING_EXTERNAL_ENVIRONMENT','calculation_model_changed':False,'formula_registry_changed':False,'normative_registry_values_changed':False,'product_database_changed':False,'meal_data_model_changed':False},
      'workspace_hotfix20_entry_ux':{'extends':'workspace_hotfix18_stage5a_final_stability','controller_path':'assets/js/89-workspace-entry-ux-v5.3.210-rc2-hf20.js','legacy_controller_path':'assets/legacy/js/89-workspace-entry-ux-v5.3.210-rc2-hf20.js','css_path':'assets/css/workspace-entry-ux-v5.3.210-rc2-hf20.css','chromium_acceptance_status':'PASSED','chromium_acceptance_report':'reports/hf20-entry-ux-browser.json','visible_view_switcher':True,'view_modes':['workspace','long'],'profile_return_action':True,'profile_label':'Имя или ФИО (необязательно)','profile_route_isolated_from_long_canvas':True,'ai_entry_methods':['search','photo','recorded_voice','audio_file'],'ai_entry_visible_at_product_search':True,'desktop_viewport_status':'PASSED','mobile_viewport_status':'PASSED','horizontal_overflow_status':'PASSED','calculation_model_changed':False,'formula_registry_changed':False,'normative_registry_values_changed':False,'product_database_changed':False,'meal_data_model_changed':False},
      'validation_evidence_policy':{'source_path':'config/validation-evidence-policy.v5.3.210-pc2.json','runtime_path':'assets/data/validation-evidence-policy.v5.3.210-pc2.js','controller_path':None,'version':policy['release_version'],'stage_status':policy['stage_status'],'sha256':sha((ROOT/'config/validation-evidence-policy.v5.3.210-pc2.json').read_bytes()),'evidence_domains':len(policy['evidence_model']),'external_validation_claim_allowed':False,'blind_cases':blind['case_count'],'blind_pack_sha256':blind['integrity']['content_sha256'],'reference_key_sha256':key['integrity']['content_sha256'],'critical_reference_cases':sum(1 for row in key['cases'] if row.get('reference',{}).get('severity')=='CRITICAL'),'release_gate':'version_matched_signed_independent_review_and_moderated_pilot','visible_status_panel':False}
    },'files':[{'path':r,'sha256':sha(d),'size':len(d),'mode':format(m,'04o')} for r,d,m in files]}
    secret=next((x for x in manifest['files'] if x['path']=='api/gemini-secret.php'),None);manifest['private_secret_sha256']=secret['sha256'] if secret else None
    if kind in {'hosting','hosting-template'}:manifest['excluded_build_surfaces']=['.github','tests','tools','quality','config','reports','release','node_modules','hosting-check.html','index-v5.3.208.html','index-v5.3.209.html','historical unreachable assets/data']
    mdata=(json.dumps(manifest,ensure_ascii=False,sort_keys=True,indent=2)+'\n').encode();sdata=(json.dumps(spdx(files,path.name),ensure_ascii=False,sort_keys=True,indent=2)+'\n').encode()
    extras=[('release-manifest.json',mdata,0o644),('release-sbom.spdx.json',sdata,0o644)]
    path.parent.mkdir(parents=True,exist_ok=True)
    with zipfile.ZipFile(path,'w') as zf:
        for rel,data,mode in sorted(files+extras,key=lambda x:x[0]):add_entry(zf,rel,data,mode)
    return {'path':str(path),'kind':kind,'sha256':sha(path.read_bytes()),'size':path.stat().st_size,'files':len(files)+2}

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--kind',choices=['hosting','hosting-template','full','source'],required=True);ap.add_argument('--output',required=True);ap.add_argument('--verify-reproducible',action='store_true');ap.add_argument('--json-out');a=ap.parse_args()
    out=Path(a.output).resolve();result=build(out,a.kind);result['reproducible']=None
    if a.verify_reproducible:
        with tempfile.TemporaryDirectory() as td:
            other=build(Path(td)/out.name,a.kind);result['reproducible']=result['sha256']==other['sha256']
            if not result['reproducible']:raise SystemExit('deterministic rebuild mismatch')
    print(json.dumps(result,ensure_ascii=False,indent=2))
    if a.json_out:
        p=Path(a.json_out);p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
if __name__=='__main__':main()
